// <auto-generated />
using System;
using Furever.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Furever.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220216053242_intialdbcreate")]
    partial class intialdbcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Furever.Entities.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RefugeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RefugeId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2 year old, Female, Cavalier King Charles Spaniel",
                            IsAvailable = true,
                            Name = "Daisy",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 year old, Male, German Sheppard",
                            IsAvailable = true,
                            Name = "Duke",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3 year old, Male, Boxer",
                            IsAvailable = true,
                            Name = "Gus",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 month old, Male, Maltese",
                            IsAvailable = true,
                            Name = "Jasper",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Age = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3 year old, Male, Corgi",
                            IsAvailable = true,
                            Name = "Kobe",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2 year old, Female, Siberian Husky",
                            IsAvailable = true,
                            Name = "Luna",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 year old, Male, Pug",
                            IsAvailable = true,
                            Name = "Milo",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Age = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 month old, Brother and Sister, Labrador Retrievers",
                            IsAvailable = true,
                            Name = "Molly and Toby",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Age = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 month old, Male, German Sheppard",
                            IsAvailable = true,
                            Name = "Rocky",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Age = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 month old, Female, Yorkshire Terrier",
                            IsAvailable = true,
                            Name = "Zoe",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Age = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 year old, Female, Gray & White Maine Coon",
                            IsAvailable = true,
                            Name = "Abby",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 month old, Male, Tri-Color Short Hair, Kitten",
                            IsAvailable = true,
                            Name = "Binx",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Age = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 year old, Female, Short Hair",
                            IsAvailable = true,
                            Name = "Jade",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Age = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 year old, Male, Gray Short Hair",
                            IsAvailable = true,
                            Name = "Jax",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 15,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 month old, Female, White Kitten",
                            IsAvailable = true,
                            Name = "Lucy",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3 month old, Female, Orange Tabby",
                            IsAvailable = true,
                            Name = "Lulu",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 month old, Male, Gray Kitten",
                            IsAvailable = true,
                            Name = "Ollie",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 month old, Male, Black and White Kitten",
                            IsAvailable = true,
                            Name = "Oreo",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 19,
                            Age = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3 month old, Female, Gray and White Kitten",
                            IsAvailable = true,
                            Name = "Rosie",
                            RefugeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Age = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "8 year old, Male, Orange and Gray Short Hair",
                            IsAvailable = true,
                            Name = "Simba",
                            RefugeId = 1
                        });
                });

            modelBuilder.Entity("Furever.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Species = "Dogs"
                        },
                        new
                        {
                            Id = 2,
                            Species = "Cats"
                        },
                        new
                        {
                            Id = 3,
                            Species = "Birds"
                        },
                        new
                        {
                            Id = 4,
                            Species = "Reptiles"
                        });
                });

            modelBuilder.Entity("Furever.Entities.Models.Favorite", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimalId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            UserId = 2
                        },
                        new
                        {
                            AnimalId = 2,
                            UserId = 2
                        },
                        new
                        {
                            AnimalId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Furever.Entities.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Furever.Entities.Models.Refuge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Refuges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Fake Avenue",
                            City = "Ottawa",
                            Email = "owner@test.com",
                            FirstName = "Owner",
                            LastName = "Test",
                            Username = "Testing"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Fake Street",
                            City = "Montreal",
                            Email = "test@owner.com",
                            FirstName = "Test",
                            LastName = "Owner",
                            Username = "Guest_01"
                        });
                });

            modelBuilder.Entity("Furever.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Test",
                            LastName = "User"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "User",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("Furever.Entities.Models.Animal", b =>
                {
                    b.HasOne("Furever.Entities.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furever.Entities.Models.Refuge", "Refuge")
                        .WithMany("Animals")
                        .HasForeignKey("RefugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Refuge");
                });

            modelBuilder.Entity("Furever.Entities.Models.Favorite", b =>
                {
                    b.HasOne("Furever.Entities.Models.Animal", "Animal")
                        .WithMany("Favorites")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furever.Entities.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furever.Entities.Models.Photo", b =>
                {
                    b.HasOne("Furever.Entities.Models.Animal", null)
                        .WithMany("Photos")
                        .HasForeignKey("AnimalId");

                    b.HasOne("Furever.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furever.Entities.Models.Animal", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Furever.Entities.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Furever.Entities.Models.Refuge", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Furever.Entities.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
